config/routes.rb
Rails.application.routes.draw do
 devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  
  resources :rezultates

  resources :notificaris do
    member do
      get :trimite
      get :trimiteneplata
      get :tz
    end
  end


  resources :programaris

  resources :pacients do

  	collection { post :import }
    resources :programaris
    resources :rezultates
 member do
      get :trimite
end
    		end



  root to: 'pacients#index'
end

app/models/notificari.rb
class Notificari < ActiveRecord::Base
	
end

app/controllers/notificaris_controller.rb
class NotificarisController < ApplicationController
 before_filter :authenticate_user!
 before_action :set_notificari, only: [:show, :edit, :update, :destroy]

  # GET /notificaris
  # GET /notificaris.json
  def index
    @notificaris = Notificari.all
  end

  # GET /notificaris/1
  # GET /notificaris/1.json
  def show
  end

  # GET /notificaris/new
  def new
    @notificari = Notificari.new
  end
def trimite
  @pacients = Pacient.all
  notificari = Notificari.find(params[:id])
   @pacients.each do |pacient|
    if pacient.nrtel.present? and pacient.nrtel.include? "07"
    ProgramariMailer.trimite(pacient,notificari).deliver
  end
  
   end
  redirect_to notificaris_url, notice: 'Notificari au fost trimise'
end
def trimiteneplata
  @pacients = Pacient.all
  notificari = Notificari.find(params[:id])
   @pacients.each do |pacient|
    if pacient.nrtel.present? and pacient.nrtel.include? "07"
    ProgramariMailer.trimiteneplata(pacient,notificari).deliver
  end
  
  
   end
  redirect_to notificaris_url, notice: 'Notificarile au fost trimise'
end
  # GET /notificaris/1/edit
  def edit
  end

  # POST /notificaris
  # POST /notificaris.json
  def create
    @notificari = Notificari.new(notificari_params)

    respond_to do |format|
      if @notificari.save
        format.html { redirect_to @notificari, notice: 'Notificarea a fost salvata' }
        format.json { render action: 'show', status: :created, location: @notificari }
      else
        format.html { render action: 'new' }
        format.json { render json: @notificari.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notificaris/1
  # PATCH/PUT /notificaris/1.json
  def update
    respond_to do |format|
      if @notificari.update(notificari_params)
        format.html { redirect_to @notificari, notice: 'Notificarea a fost modificata.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notificari.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notificaris/1
  # DELETE /notificaris/1.json
  def destroy
    @notificari.destroy
    respond_to do |format|
      format.html { redirect_to notificaris_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notificari
      @notificari = Notificari.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notificari_params
      params.require(:notificari).permit(:text, :pacient_id, :var, :var1, :var2, :var3, :var4, :var5)
    end
end

app/helpers/notificaris_helper.rb
module NotificarisHelper
end

app/views/notificaris/_form.html.erb
<%= simple_form_for @notificari, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :text , :as => :text, label: 'Continut notificare:', placeholder: 'Introdu continutul notificarii' , input_html: { :rows => 10 } %>
 
  <div class="form-actions">
    <%= f.button :submit,"Salveaza", :class => 'btn-primary' %>
    <%= link_to 'Anuleaza',
                notificaris_path, :class => 'btn' %>
  </div>
<% end %>

app/views/notificaris/edit.html.erb
<%- model_class = Notificari -%>
<div class="page-header">
  <h1>Editeaza notificarea</h1>
</div>
<%= render :partial => 'form' %>

app/views/notificaris/index.html.erb
<%- model_class = Notificari -%>
<div class="page-header">
  <h1>Notificari</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name("Continut notificare") %></th>
      
      <th>Optiuni</th>
    </tr>
  </thead>
  <tbody>
    <% @notificaris.each do |notificari| %>
      <tr>
        <td><%= link_to notificari.id, notificari_path(notificari) %></td>
        <td><%= notificari.text %></td>
        
        <td>
          <%= link_to 'Modifica notificare',
                      edit_notificari_path(notificari), :class => 'btn btn-mini btn-info' %>
                      <%= link_to 'Trimite pacientilor',
                      trimite_notificari_path(notificari), :class => 'btn btn-mini btn-danger' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Notificare noua',
            new_notificari_path,
            :class => 'btn btn-primary' %>

app/views/notificaris/new.html.erb
<%- model_class = Notificari -%>
<div class="page-header">
  <h1>Notificare noua</h1>
</div>
<%= render :partial => 'form' %>

app/views/notificaris/show.html.erb
<%- model_class = Notificari -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @notificari.text %></dd>
  
</dl>

<div class="form-actions">
  <%= link_to 'Inapoi la lista de notificari',
              notificaris_path, :class => 'btn btn-info'  %>
  <%= link_to 'Modifica notificarea',
              edit_notificari_path(@notificari), :class => 'btn btn-info' %>
  <%= link_to 'Sterge notificarea',
              notificari_path(@notificari),
              :method => 'delete',
              :data => { :confirm => 'Esti sigur ca vrei sa stergi notificarea?' },
              :class => 'btn btn-danger' %>
</div>