config/routes.rb
Rails.application.routes.draw do
 devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  
  resources :rezultates

  resources :notificaris do
    member do
      get :trimite
      get :trimiteneplata
      get :tz
    end
  end


  resources :programaris

  resources :pacients do

  	collection { post :import }
    resources :programaris
    resources :rezultates
 member do
      get :trimite
end
    		end



  root to: 'pacients#index'
end

app/models/pacient.rb
class Pacient < ActiveRecord::Base
	has_many :programaris
	has_many :rezultates
  validates_presence_of :nume, :message => "EROARE:Campul nu poate fi gol!!!"
  validates_presence_of :prenume,  :message => "EROARE:Campul nu poate fi gol!!!"
  validates_presence_of :adresa, :message => "EROARE:Campul nu poate fi gol!!!"
  validates_presence_of :nrtel, :message => "EROARE:Campul nu poate fi gol!!!"
 validates_presence_of :email, :message => "EROARE:Campul nu poate fi gol!!!"
 validates_presence_of :var, :message => "EROARE:Trebuie aleasa o optiune!!!"
validates_presence_of :var1, :message => "EROARE:Trebuie aleasa o optiune!!!"
	def self.search(search)
	if search
					

		where('nume LIKE ? OR prenume LIKE ?  OR nrtel LIKE ? OR adresa LIKE ? OR email LIKE ?',"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")		
	else
		all
	end
end

	

end

app/controllers/pacients_controller.rb
class PacientsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_pacient, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  # GET /pacients
  # GET /pacients.json
  def index
    @pacients = Pacient.search(params[:search]).order(sort_column + ' ' + sort_direction ).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /pacients/1
  # GET /pacients/1.json
  def show
      @pacient = Pacient.find(params[:id])
  respond_to do |format|
          format.html
          format.pdf do
          pdf = PacientPdf.new(@pacient)
          send_data pdf.render, filename: "Fisa #{@pacient.prenume} #{@pacient.nume}",
                                type: "application/pdf",
                                disposition: "inline"

    end
  end
  end
def trimite
  @pacient = Pacient.find(params[:id])
  ProgramariMailer.fisa(@pacient).deliver
  redirect_to pacients_url, notice: 'Fisa a fost trimisa'
end
  # GET /pacients/new
  def new
    @pacient = Pacient.new
  end

  # GET /pacients/1/edit
  def edit
  end

  # POST /pacients
  # POST /pacients.json
  def create
    @pacient = Pacient.new(pacient_params)

    respond_to do |format|
      if @pacient.save
        format.html { redirect_to @pacient, notice: 'Pacient salvat cu succes' }
        format.json { render :show, status: :created, location: @pacient }
      else
        format.html { render :new }
        format.json { render json: @pacient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacients/1
  # PATCH/PUT /pacients/1.json
  def update
    respond_to do |format|
      if @pacient.update(pacient_params)
        format.html { redirect_to @pacient, notice: 'Date pacient modificate cu succes.' }
        format.json { render :show, status: :ok, location: @pacient }
      else
        format.html { render :edit }
        format.json { render json: @pacient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacients/1
  # DELETE /pacients/1.json
  def destroy
    @pacient.destroy
    respond_to do |format|
      format.html { redirect_to pacients_url, notice: 'Pacient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pacient
      @pacient = Pacient.find(params[:id])
    end
    def sort_column
      Pacient.column_names.include?(params[:sort]) ? params[:sort] : "nume"
    end
    def sort_direction
       %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def pacient_params
      params.require(:pacient).permit(:nume, :prenume, :adresa, :nrtel, :email, :var, :var1, :var2, :var3, :var4, :var5)
    end
end

app/helpers/pacients_helper.rb
module PacientsHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
		link_to title, params.merge(:sort => column, :direction =>direction, :page => nil)
		
	end
end

app/views/pacients/_form.html.erb
<%= simple_form_for @pacient, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nume , :placeholder => 'Nume pacient...',input_html: {size: 70} %><br>
  <%= f.input :prenume ,:placeholder => 'Prenume pacient...',input_html: {size: 70}%><br>
  <%= f.input :var,label: "CNP", :placeholder => "CNP pacient....",input_html: {size: 70} %>
  <%= f.input :adresa,:placeholder => 'Adresa pacient...',input_html: {size: 70} %><br>
  <%= f.input :nrtel,label: "Telefon", :placeholder => 'Numar de telefon pacient...',input_html: {size: 70} %><br>
  <%= f.input :email,:placeholder => 'Email pacient...',input_html: {size: 70} %>
  <%= f.input :var,label: "Medic", :placeholder => 'Medic la care este programat...', collection:  ['Raluca Enuca', 'Bogdan Chisevescu '] %><br>
   <%= f.input :var1, label: "Trimitere notificari prin sms:", collection: ['DA', 'NU'] %>
 <br><br>
  <div class="form-actions">
    <%= f.button :submit,'Salveaza', :class => 'btn-primary' %>
    <%= link_to 'Anuleaza',
                pacients_path, :class => 'btn' %>
  </div>
<% end %>

app/views/pacients/edit.html.erb
<%- model_class = Pacient -%>
<div class="page-header">
  <h1>Modifica date pacient</h1>
</div>
<%= render :partial => 'form' %>

app/views/pacients/index.html.erb
<%- model_class = Pacient -%>
<div class="page-header">
  <h1>Lista pacienti </h1>
  <%= link_to 'Pacient nou',
            new_pacient_path,
            :class => 'btn btn-primary' %>
  <%= simple_form_for pacients_path, :html => { :class => 'form-horizontal pull-right' }, :method => 'get' do%>
<% hidden_field_tag :direction, params[:direction] %>
<% hidden_field_tag :sort, params[:sort] %>
<p>
    <%= text_field_tag :search, params[:search] %>

    <%= submit_tag "Cauta", :denumire => nil, :class => 'btn btn-info' %>
  </p>
<% end %>
</div>
<table class="table table-striped">
  <thead>

    <tr>
      <th><%= model_class.human_attribute_name(:nume) %></th>
      <th><%= model_class.human_attribute_name(:prenume) %></th>
     
      <th><%= model_class.human_attribute_name(:adresa) %></th>
      <th><%= model_class.human_attribute_name("Telefon") %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th> </th>
      <th>Optiuni</th>
    </tr>
  </thead>
  <tbody>
    <% @pacients.each do |pacient| %>
      <tr>
       <td><%= link_to pacient.nume, pacient_path(pacient)  %></td>
        <td><%= link_to pacient.prenume, pacient_path(pacient)  %></td>
        
        <td><%= pacient.adresa %></td>
        <td><%= pacient.nrtel %></td>
        <td><%= pacient.email %></td>
        <td> </td>
        <td>
          <%= link_to 'Modifica date pacient',
                      edit_pacient_path(pacient), :class => 'btn btn-mini btn-info' %>
                      <%= link_to 'Programeaza',
                      new_pacient_programari_path(pacient),'data-no-turbolink' => true,:class => 'btn btn-mini btn-danger' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @pacients %><br>
<%= link_to 'Pacient nou',
            new_pacient_path,
            :class => 'btn btn-primary' %>

app/views/pacients/new.html.erb
<%- model_class = Pacient -%>
<div class="page-header">
  <h1>Pacient nou</h1><br>
  <h4>Completeaza datele pacientului</h4><br>
  <h5>Campurile cu steluta sunt obligatorii</h5>
</div>
<%= render :partial => 'form' %>

app/views/pacients/show.html.erb
<%- model_class = Pacient -%>
<div class="page-header">
  <h1><%= @pacient.prenume  %> <%= @pacient.nume %></h1><br>
  <h4>Datele de identificare ale pacientului</h4>
</div>

<dl class="dl-horizontal">
 
 <dt><strong><%= model_class.human_attribute_name(:CNP) %>:</strong></dt>
  <dd><%= @pacient.var %></dd>
  <dt><strong><%= model_class.human_attribute_name(:adresa) %>:</strong></dt>
  <dd><%= @pacient.adresa %></dd>
  <dt><strong><%= model_class.human_attribute_name("Telefon") %>:</strong></dt>
  <dd><%= @pacient.nrtel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @pacient.email %></dd>
 
</dl>

<div class="form-actions">
  <%= link_to 'Inapoi la lista de pacienti',
              pacients_path, :class => 'btn btn-info'  %>
  <%= link_to 'Modifica date pacient',
              edit_pacient_path(@pacient), :class => 'btn btn-info' %>
  <%= link_to 'Programeaza pacient',
              new_pacient_programari_path(@pacient), 'data-no-turbolink' => true, :class => 'btn btn-danger' %>   
              <%= link_to 'Diagnostic nou',
              new_pacient_rezultate_path(@pacient), :class => 'btn btn-info' %>  
  <%= link_to "Fisa medicala PDF", pacient_path(@pacient, format: "pdf"), :class => 'btn btn-info' %>
  <%= link_to "Trimite fisa medicala", trimite_pacient_path(@pacient), :class => 'btn btn-warning' %>        
  
</div>
<br><br><br>
<h2>Istoric  programari </h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name('ID programare') %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:ora) %></th>
      <th><%= model_class.human_attribute_name("Medic") %></th>
      <th><%= model_class.human_attribute_name("Tip investigatie") %></th>
     
     
    </tr>
  </thead>
  <tbody>
  <% @pacient.programaris.each do |programari| %>
    
      <tr>
        <td><%= link_to programari.id, programari_path(programari) %></td>
        <td><%= programari.data %></td>
        <td><%= programari.ora %></td>
        <td><%= programari.medicul %></td>
        <td><%= programari.tip %></td>
        <% end %>
        </tr>
        </tbody>
        </table>
        <br><br>
        <h2>Istoric  diagnostice pacient </h2>
        <table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name('ID Diagnostic') %></th>
      <th><%= model_class.human_attribute_name('Rezultat Examinare') %></th>
      <th><%= model_class.human_attribute_name('Diagnostic') %></th>
      <th><%= model_class.human_attribute_name('Imagini diagnostic') %></th>
     
     
     
    </tr>
  </thead>
  <tbody>
  <% @pacient.rezultates.each do |rezultate| %>
    
      <tr>
        <td><%= link_to rezultate.id, rezultate_path(rezultate) %></td>
        <td><%= rezultate.exam %></td>
        <td><%= rezultate.diagn %></td>
        
        <td><%= image_tag rezultate.image_url(:thumb).to_s %><br>
        <% if rezultate.image_url.present? %>
        <%= link_to 'Vezi imaginea', rezultate.image_url %></td>
       <% end %>
        <% end %>
        </tr>
        </tbody>
        </table>
        <br><br>
        